// examples/views/vradiobutton/index.vue
<template>
  <demo-wrapper title="VRadioButton 单选按钮组">
    <demo-card title="basic">
      <v-radio-button label="关键城市" v-model="value" :columns="columns" input-align="right"/>
    </demo-card>
    <demo-card title="color">
      <v-radio-button label="关键城市" v-model="value" :columns="columns" color="danger"/>
    </demo-card>
    <demo-card title="disabled">
      <v-radio-button label="关键城市" v-model="value" :columns="columns" disabled/>
    </demo-card>
    <demo-card title="readonly">
      <v-radio-button label="关键城市" v-model="value" :columns="columns" readonly/>
    </demo-card>
    <README/>
  </demo-wrapper>
</template>

<script>
import README from './README.md'

export default {
  name: 'vradiobutton',
  data() {
    return {
      value: 1,
      columns: [
        { label: '上海', value: 1 },
        { label: '北京', value: 2, disabled: true },
        { label: '广州', value: 3 },
        { label: '深圳', value: 4 },
      ]
    }
  },
  components: {
    README
  }
}
</script>

// lib/v-radio-button/v-radio-button.jsx
export default {
  name: 'VRadioButton',
  model: {
    prop: 'value',
    event: 'input'
  },
  props: {
    value: [String, Number],
    columns: {
      type: Array,
      default: () => [],
      required: true
    },
    color: {
      type: String,
      default: 'primary' // primary、info、warning、danger
    },
    disabled: {
      type: Boolean,
      default: false
    },
    readonly: {
      type: Boolean,
      default: false
    },
    prop: {
      type: Object,
      default: () => ({ label: 'label', value: 'value' })
    }
  },
  computed: {
    _columns() {
      return Array.from(this.columns).map((item) => ({
        ...item,
        text: item[this.prop.label],
        value: item[this.prop.value],
      }))
    }
  },
  methods: {
    onClick(item, index) {
      this.$emit('input', item.value, index)
    },
    active(item, index) {
      return item.value === this.value ? this.color : 'default'
    }
  },
  render() {
    const data = {
      attrs: {
        ...this.$attrs,
        disabled: this.disabled,
        readonly: this.readonly,
      },
    }
    return (
      <van-field
        {...data}
        value={this.value}
        input-align="right"
        center={true}
      >
        <template slot="input">
          {
            this._columns.map((item, index) => {
              return (
                <van-button
                  type={this.active(item, index)}
                  size="mini"
                  disabled={this.disabled || this.readonly || item.disabled}
                  onClick={() => this.onClick(item, index)}
                >
                  {item.label}
                </van-button>
              )
            })
          }
        </template>
      </van-field>
    )
  }
}
